### ISSUE TITLE
requirejs.optimize issue with Gulp usage

### ISSUE THREAD

**Issue by ORESoftware** [jrburke/requirejs#1426]
I can successfully run

```
r.js -o ./build/build.js
```

with this config

```javascript
({
    //"optimizeAllPluginResources": true,
    "allowSourceOverwrites": false,
    "preserveLicenseComments": false,
    "findNestedDependencies": false,
    "baseUrl": "../public/static",
    "name": "app/js/main",
    "mainConfigFile": "../public/static/app/js/main.js",
    "out": "../public/static/app/optimized/optimized.js",
    "paths" :{
        requireLib : 'vendor/require',
        jqueryUI: "empty:",
        jqueryUI_CSS: "empty:"
    },
    "include": ['requireLib','app/js/application','app/js/boot'],
    "stubModules":['text']
})
```

works like a charm

but when I try to use requirejs.optimize with the same exact config like so:

```javascript
gulp.task('optimize', [], function (done) {

    var config = {
  
        "allowSourceOverwrites": false,
        "preserveLicenseComments": false,
        "findNestedDependencies": false,
        "baseUrl": "./public/static",
        "name": "app/js/main",
        "mainConfigFile": "./public/static/app/js/main.js",
        "out": "./public/static/app/optimized/optimized.js",
        "paths" :{
            requireLib : 'vendor/require',
            jqueryUI: "empty:",
            jqueryUI_CSS: "empty:"
        },

        "include": ['requireLib','app/js/application','app/js/boot'],
        "stubModules":['text']
     
    };

    requirejs.optimize(config, function (err,results) {
        console.log('error:',err,'results:',results);
        done(err);
    });

});
```

it *almost* works, but at the very end I get this:

```javascript
CACSVML-13295:sc-admin-ui-express amills001c$ gulp optimize
[18:25:59] Using gulpfile ~/WebstormProjects/ORESoftware/sc-admin-ui-express/gulpfile.js
[18:25:59] Starting 'optimize'...
[18:26:12] 'optimize' errored after 13 s
[18:26:12] Error: 
  at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:107:17)
    at Gulp.Orchestrator._emitTaskDone (/Users/amills001c/WebstormProjects/ORESoftware/sc-admin-ui-express/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/amills001c/WebstormProjects/ORESoftware/sc-admin-ui-express/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/amills001c/WebstormProjects/ORESoftware/sc-admin-ui-express/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/amills001c/WebstormProjects/ORESoftware/sc-admin-ui-express/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at /Users/amills001c/WebstormProjects/ORESoftware/sc-admin-ui-express/gulpfile.js:168:9
    at /Users/amills001c/WebstormProjects/ORESoftware/sc-admin-ui-express/node_modules/requirejs/bin/r.js:3034:37
    at /Users/amills001c/WebstormProjects/ORESoftware/sc-admin-ui-express/node_modules/requirejs/bin/r.js:2982:25
```

I am having a hard time determining if this is an r.js problem or gulp.js problem, any ideas?

**Comment by ORESoftware** [comment]
my guess is that instead of this:

```javascript
   requirejs.optimize(config, function (err, buildResponse) {
        console.log('build-response:',buildResponse);
        done(err);
    });
```

i need to do this:

```javascript
   requirejs.optimize(config, function (buildResponse) {
        console.log('build-response:',buildResponse);
        done(null);
    },function(err){
        done(err);
    });
```

**Comment by jrburke** [comment]
Correct, the optimize function takes the error handler as the third argument.
